import { NextRequest } from 'next/server';
import { adminAuth, adminRtdb } from '@/lib/firebase/admin';
import { getUserFromRequest } from '@/lib/firebase/auth-server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface WorkspaceSummary {
  workspaceId: string;
  name: string | null;
  slug: string | null;
  createdAt: number | null;
  lastActive: number | null;
  // Who built it — the lead. Email(s) come from the workspace member list; the
  // display name (if any) from the creator's Google account.
  builderEmail: string | null;
  builderName: string | null;
  members: string[];
  personas: number;
  channels: number;
  buckets: number;
  entityCollections: number;
  styleTemplates: number;
  calendarSlots: number;
  creatives: number;
  hasIntake: boolean;
  // Partial-intake signals — what a stalled onboarding still captured.
  website: string | null;
  writeupSeed: string | null;
  currentStep: number | null;
  scrapeStatus: string | null;
}

// Marketing-tool member emails are stored with '@' → '_AT_' and '.' → '_DOT_'
// (see marketingCommon.js encEmail). Reverse it for display.
function decEmail(enc: string): string {
  return enc.replace(/_AT_/g, '@').replace(/_DOT_/g, '.');
}

function asList(v: unknown): Record<string, unknown>[] {
  return Object.values((v as Record<string, unknown>) || {}) as Record<string, unknown>[];
}

function joinArr(v: unknown): string {
  return (Array.isArray(v) ? v : [v]).filter(Boolean).join(' · ');
}

// Mirrors exportWorkspace() in functions/index.js — same markdown brief, built
// server-side here so the admin page doesn't depend on the Cloud Function.
function buildOntologyMarkdown(wsid: string, v: Record<string, any>): string {
  const meta = v.meta || {};
  const intake = v.intake || {};
  const personas = asList(v.personas) as any[];
  const channels = asList(v.channels) as any[];
  const buckets = asList(v.buckets) as any[];
  const entityCollections = asList(v.entityCollections) as any[];
  const entities = (v.entities || {}) as Record<string, Record<string, any>>;
  const styleTemplates = asList(v.styleTemplates) as any[];

  return [
    `# ${meta.name || 'Brand'} — Marketing Brief`,
    '',
    `_Workspace ${wsid}${meta.created_at ? `, created ${new Date(meta.created_at).toISOString().slice(0, 10)}` : ''} — Marketing Engine._`,
    '',
    intake.website && intake.website !== '__skipped__' ? `**Website:** ${intake.website}` : '',
    '',
    '## What this brand does',
    intake.writeup ||
      (intake.writeup_seed
        ? `_(no interview answer — from website scrape)_\n\n${intake.writeup_seed}`
        : '_(not provided)_'),
    '',
    '## Who they sell to',
    intake.customer_types || '_(not provided)_',
    '',
    `**Funnel focus this period:** ${intake.funnel_focus || 'mixed'}`,
    `**Marketing stack:** ${intake.marketing_stack || '_(not provided)_'}`,
    '',
    '## Personas',
    personas.length === 0
      ? '_(none yet)_'
      : personas
          .map(p =>
            [
              `### ${p.name} (${p.age_range || ''}, ${p.occupation || ''})`,
              `**Voice:** ${p.voice_to_use || ''}`,
              `**Motivations:** ${joinArr(p.motivations)}`,
              `**Pain points:** ${joinArr(p.pain_points)}`,
              `**Where they hang out:** ${joinArr(p.where_they_hang_out)}`,
              `**Sample objection:** ${p.sample_objection || ''}`
            ].join('\n')
          )
          .join('\n\n'),
    '',
    '## Channels',
    channels.length === 0
      ? '_(none yet)_'
      : channels.map(c => `- **${c.platform}** — ${c.handle_url || ''} — ${c.what_we_post || ''}`).join('\n'),
    '',
    '## Content buckets',
    buckets.length === 0
      ? '_(none yet)_'
      : buckets
          .map(b => `- **${b.name}** _(${b.function})_, ${b.frequency_count}/${b.frequency_per} — ${b.description || ''}`)
          .join('\n'),
    '',
    '## Entity collections',
    entityCollections.length === 0
      ? '_(none yet)_'
      : entityCollections
          .map(c => {
            const ents = Object.values(entities[c.slug] || {}).map((e: any) => e.name);
            return `- **${c.display_name}** ${c.icon || ''} (${ents.length}): ${ents.slice(0, 10).join(', ')}${ents.length > 10 ? ', …' : ''}`;
          })
          .join('\n'),
    '',
    '## Style direction',
    styleTemplates.length === 0
      ? '_(none yet)_'
      : styleTemplates
          .map(s => `- Palette: ${(s.palette || []).join(', ')} — Mood: ${(s.mood || []).join(', ')}`)
          .join('\n'),
    '',
    '— Generated by the Marketing Engine.'
  ].join('\n');
}

export async function GET(req: NextRequest) {
  const user = await getUserFromRequest(req);
  if (!user) return new Response('unauthorized', { status: 401 });
  if (!user.operator) return new Response('forbidden — operator only', { status: 403 });

  // Lightweight activity summary for the workspace tab badge — per-workspace
  // activity timestamps (created / last active) only, no content.
  if (req.nextUrl.searchParams.get('summary')) {
    const snap = await adminRtdb().ref('Workspaces').once('value');
    const all = (snap.val() || {}) as Record<string, any>;
    const recentAt = Object.values(all)
      .map(v => {
        const meta = (v as any)?.meta || {};
        return Math.max(meta.created_at ?? 0, meta.last_active ?? 0);
      })
      .filter(t => t > 0)
      .sort((a, b) => b - a)
      .slice(0, 50);
    return Response.json({ recentAt, latestAt: recentAt[0] ?? 0 });
  }

  const workspaceId = req.nextUrl.searchParams.get('workspaceId');

  if (workspaceId) {
    const snap = await adminRtdb().ref(`Workspaces/${workspaceId}`).once('value');
    const v = snap.val();
    if (!v) return new Response('workspace not found', { status: 404 });
    const meta = v.meta || {};
    return Response.json({
      workspaceId,
      name: meta.name ?? null,
      slug: meta.slug ?? null,
      markdown: buildOntologyMarkdown(workspaceId, v)
    });
  }

  const snap = await adminRtdb().ref('Workspaces').once('value');
  const all = (snap.val() || {}) as Record<string, any>;

  // Resolve creator display names from Auth, cached per uid so a workspace list
  // does at most one lookup per distinct builder.
  const nameCache = new Map<string, string | null>();
  const nameFor = async (uid: string | undefined): Promise<string | null> => {
    if (!uid) return null;
    if (nameCache.has(uid)) return nameCache.get(uid) ?? null;
    let name: string | null = null;
    try {
      const u = await adminAuth().getUser(uid);
      name = u.displayName ?? null;
    } catch {
      name = null;
    }
    nameCache.set(uid, name);
    return name;
  };

  const workspaces: WorkspaceSummary[] = await Promise.all(
    Object.entries(all).map(async ([id, v]) => {
      const meta = v.meta || {};
      let calendarSlots = 0;
      Object.values(v.calendar || {}).forEach((slots: any) => {
        calendarSlots += Object.keys(slots || {}).length;
      });
      const members = Object.keys(v.members || {}).map(decEmail);
      return {
        workspaceId: id,
        name: meta.name ?? null,
        slug: meta.slug ?? null,
        createdAt: meta.created_at ?? null,
        lastActive: meta.last_active ?? null,
        builderEmail: members[0] ?? null,
        builderName: await nameFor(meta.created_by),
        members,
        personas: asList(v.personas).length,
        channels: asList(v.channels).length,
        buckets: asList(v.buckets).length,
        entityCollections: asList(v.entityCollections).length,
        styleTemplates: asList(v.styleTemplates).length,
        calendarSlots,
        creatives: asList(v.creatives).length,
        hasIntake: Boolean(v.intake && (v.intake.writeup || v.intake.customer_types)),
        website:
          v.intake?.website && v.intake.website !== '__skipped__' ? v.intake.website : null,
        writeupSeed: v.intake?.writeup_seed
          ? String(v.intake.writeup_seed).slice(0, 200)
          : null,
        currentStep: v.intake?.current_step ?? null,
        scrapeStatus: v.scrapeJob?.status ?? null
      };
    })
  );
  workspaces.sort((a, b) => (b.createdAt ?? 0) - (a.createdAt ?? 0));

  return Response.json({ workspaces });
}
