'use client';

import { useEffect, useState } from 'react';
import type { SynthesisClaim } from '@/lib/model/claims';
import { useAuth } from './AuthProvider';

/**
 * Renders the synthesis as the "posture-shift" — the so-what beat between
 * the abstract one-liner and the nine cards. This is the layer that makes
 * the reader feel "I see my business differently now."
 *
 * No new computation: the synthesis claim already exists (or is lazy-
 * generated by the existing /api/companies/[id]/synthesis endpoint for
 * older companies). This component is purely a rendering pass.
 */
export function PostureShift({
  synthesis,
  companyId,
  canFetch
}: {
  synthesis: SynthesisClaim | null;
  companyId: string | null;
  canFetch: boolean;
}) {
  const { getToken } = useAuth();
  const [lazy, setLazy] = useState<SynthesisClaim | null>(null);
  const [loading, setLoading] = useState(false);

  const resolved = synthesis ?? lazy;

  // Auto-load synthesis once on mount for owners on existing companies that
  // don't have one yet. Quiet — no spinner; the section just blinks in
  // when ready.
  useEffect(() => {
    if (!companyId || !canFetch || resolved || loading) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      try {
        const token = await getToken();
        const res = await fetch(`/api/companies/${companyId}/synthesis`, {
          method: 'POST',
          headers: token ? { authorization: `Bearer ${token}` } : {}
        });
        if (!res.ok) return;
        const data = (await res.json()) as { claim?: SynthesisClaim };
        if (!cancelled && data.claim) setLazy(data.claim);
      } catch {
        // silent — the page still has the one-liner above
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [companyId, canFetch, resolved, loading, getToken]);

  if (!resolved) {
    if (loading) {
      return (
        <p className="mt-2 text-sm italic text-ink-400">
          Writing the deeper read…
        </p>
      );
    }
    return null;
  }

  return (
    <div className="space-y-3 text-[16px] leading-relaxed text-ink-800">
      {resolved.content.text.split('\n\n').map((p, i) => (
        <p key={i}>{p}</p>
      ))}
      {resolved.content.lowConfidence && (
        <p className="text-[11px] uppercase tracking-wider text-rose-700">
          Low confidence — based on sparse evidence
        </p>
      )}
    </div>
  );
}
